#!/usr/bin/lua
require 'nixio'
nixio.signal(2,"dfl")
addr=arg[1]
port=arg[2]
inet=arg[3]
t=5
if arg[4]~=nil then
	t=arg[4]
end
socket=nixio.socket(inet,"stream")
socket:setopt("socket","rcvtimeo",t)
socket:setopt("socket","sndtimeo",t)
--print("Detecting ports on server: "..addr..":"..port.."...")
if socket:connect(addr,port) then
	--print("Port open")
	os.exit(0)
else
	--print("Port closed")
	os.exit(1)
end
socket:close()
