#!/bin/sh
if [ "$1" = v6 ];then
	ipset -N over_v6 hash:net family inet6 2>/dev/null
	awk '!/^$/&&!/^#/{printf("add over_v6 %s\n",$0)}' /tmp/overwall/ipv6.txt > /tmp/ipv6.ipset
	ipset -F over_v6 2>/dev/null
	ipset -R < /tmp/ipv6.ipset 2>/dev/null
else
	ipset -N over_v4 hash:net 2>/dev/null
	awk '!/^$/&&!/^#/{printf("add over_v4 %s\n",$0)}' /tmp/overwall/ipv4.txt > /tmp/ipv4.ipset
	ipset -F over_v4 2>/dev/null
	ipset -R < /tmp/ipv4.ipset 2>/dev/null
fi
rm -f /tmp/ipv*.ipset
