#!/bin/sh
NAME=overwall

uci_get_by_name(){
	ret=$(uci -q get $NAME.$1.$2)
	echo ${ret:=$3}
}

uci_get_by_type(){
	ret=$(uci -q get $NAME.@$1[0].$2)
	echo ${ret:=$3}
}

redir_tcp=$1
kcp=$2
redir_udp=$3
redir_yb=$4
redir_nf=$5
redir_cu=$6
redir_tg=$7
smartdns=$8
chinadns=$9
socks5=${10}
server_count=${11}
server=`cat /tmp/etc/$NAME.include | grep udp_ip= | cut -d = -f2`;echo $server | grep -q : && server=[$server]
GLOBAL_SERVER=$(uci_get_by_type global global_server)
kcp_port=$(uci_get_by_name $GLOBAL_SERVER kcp_port)
server_port=$(uci_get_by_name $GLOBAL_SERVER server_port)
password=$(uci_get_by_name $GLOBAL_SERVER kcp_password)
kcp_param=$(uci_get_by_name $GLOBAL_SERVER kcp_param)
gfw_mode=$(uci_get_by_type global gfw_mode 0)
[ "$password" != "" ] && password="--key "${password}

log(){
	echo "$(date +'%Y' | awk '{print ($1-1911)}')-$(date +'%m-%d %H:%M:%S') Over Montior: $*" >> /tmp/$NAME.log
}

res(){
	/etc/init.d/$NAME restart
}

while :;do
	sleep 30
#redir tcp
	if [ $redir_tcp -gt 0 ] && [ $(ps -ww | grep overwall-tcp | grep -v grep | wc -l) -lt $redir_tcp ];then
		log "Redir TCP Error. Restart!"
		res
	fi
#kcptun
	if [ $kcp = 1 ] && [ $(ps -ww | grep kcptun-client | grep -v grep | wc -l) = 0 ];then
		log "KCPTUN Error. Restart!"
		killall -q -9 kcptun-client
		$(which kcptun-client) -r $server:$kcp_port -l :$server_port $password $kcp_param &
	fi
#redir udp
	if [ $redir_udp = 1 ] && [ $(ps -ww | grep overwall-udp | grep -v grep | wc -l) = 0 ];then
		log "Redir UDP Error. Restart!"
		res
	fi
#redir youtube
	if [ $redir_yb = 1 ] && [ $(ps -ww | grep overwall-yb | grep -v grep | wc -l) = 0 ];then
		log "Redir Youtube Error. Restart!"
		res
	fi
#redir netflix
	if [ $redir_nf = 1 ] && [ $(ps -ww | grep overwall-nf | grep -v grep | wc -l) = 0 ];then
		log "Redir Netflix Error. Restart!"
		res
	fi
#redir custom
	if [ $redir_cu = 1 ] && [ $(ps -ww | grep overwall-cu | grep -v grep | wc -l) = 0 ];then
		log "Redir Custom Error. Restart!"
		res
	fi
#redir telegram
	if [ $redir_tg = 1 ] && [ $(ps -ww | grep overwall-tg | grep -v grep | wc -l) = 0 ];then
		log "Redir Telegram Error. Restart!"
		res
	fi
#smartdns
	if [ $smartdns = 1 ] && [ $(ps -ww | grep smartdns | grep -v grep | wc -l) = 0 ];then
		log "SmartDNS Error. Restart!"
		killall -q -9 smartdns
		$(which smartdns) -f -c /var/etc/smartdns/smartdns.conf >/dev/null 2>&1 &
	fi
#chinadns-ng
	if [ $chinadns = 1 ] && [ $(ps -ww | grep chinadns-ng | grep -v grep | wc -l) = 0 ];then
		log "ChinaDNS-NG Error. Restart!"
		$(which chinadns-ng) -l 5337 -c '127.0.0.1#5336' -t '127.0.0.1#5335' -4 over_v4 -6 over_v6 $([ $gfw_mode = 0 ] && echo -g /tmp/overwall/gfw.list) >/dev/null 2>&1 &
	fi
#localsocks
	if [ $socks5 = 1 ] && [ $(ps -ww | grep overwall-socks5 | grep -v grep | wc -l) = 0 ];then
		log "Global Socks Server Error. Restart!"
		res
	fi
#server
	if [ $server_count -gt 0 ] && [ $(ps -ww | grep overwall-server | grep -v grep | wc -l) -lt $server_count ];then
		log "Overwall Server Error. Restart!"
		res
	fi
done
