#!/bin/sh
[ "$1" = gfw ] && M=1
C=$2
D=$3
E=0
T=1
shift 3
X=/usr/share/overwall/curl
Y=Overwall/rules

nf(){
	[ $(uci -q get overwall.@global[0].nf_ip) ] || return
	A=$($X 1 $Y/Netflix "-Lfsm 5" 20 2) || return
	A=$(echo "$A" | base64 -d)
	for i in $A;do ipset add $1 $i 2>/dev/null;done
}

tg(){
	A=$($X 1 $Y/Telegram "-Lfsm 5" 20 2) || return
	A=$(echo "$A" | base64 -d)
	for i in $A;do ipset add $1 $i 2>/dev/null;done
}

for i in $*;do
	while ! nslookup $i >/dev/null 2>&1;do :;done
done

case $C in
	1)nf netflix;;
	2|4)nf blacklist;;
	3)nf youtube;;
esac

case $D in
	0)T=;;
	1)tg telegram;;
	2)tg blacklist;;
	3)tg youtube;;
	4)tg netflix;;
	5)tg custom;;
esac

if [ $M ];then
	if [ "$(uci -q get overwall.@global[0].pre_ip)" = 1 ];then
		[ $T ] || tg blacklist
		B=1
		while ! A=$(nslookup -q=TXT _spf.google.com | grep text | sed -e 's/"v=spf1//' -e 's/ ~all"//' -e 's/ include:/\n/g' | grep -v text);do
			[ $B -ge 20 ] && break || let B++
			sleep 2
		done
		for i in $A;do
			B=1
			while ! nslookup -q=TXT $i >/dev/null 2>&1;do
				[ $B -ge 20 ] && break || let B++
				sleep 2
			done
			B=$(nslookup -q=TXT $i | sed -e 's/"v=spf1//' -e 's/ ~all"//' -e 's/ ip.:/\n/g' | grep -E -o '([0-9]{1,3}\.){3}[0-9]{1,3}/[0-9]{1,2}')
			for i in $B;do ipset add blacklist $i 2>/dev/null;done
		done
	fi

	if [ "$(uci -q get overwall.@global[0].pre_domain)" = 1 ];then
		A=$(cat /etc/overwall/preload.list)
		for i in $A;do
			B=1
			while ! nslookup $i >/dev/null 2>&1;do
				[ $B -ge 20 ] && break || let B++
				sleep 2
			done
		done
	fi
fi
