#!/bin/sh
[ "$1" = --First ] && A=Y || A=N
# 防止重複啟動
[ -f /var/lock/overwall.lock -a $A = N ] && exit 1
LOCK=/var/lock/overwall-update.lock
[ -f $LOCK ] && exit 1
touch $LOCK
DIR=/usr/share/overwall
TMP=/tmp/overwall
X=$(lua /usr/share/overwall/auth A)/2axgmlws/KkFCtZkeAP
Y=$(lua /usr/share/overwall/auth B)
Z="lua /usr/share/overwall/auth C"

log(){
	[ $A = N ] && echo "$(date +'%Y-%m-%d %H:%M:%S') $*" >> /tmp/overwall.log
}

clean(){
	echo "$(date +'%Y-%m-%d %H:%M:%S') Over Rules     : Download failed" >> /tmp/overwall.log
	rm -f $LOCK
	exit 1
}

if [ $A = Y ];then
	mkdir -p $TMP
	r=1
	while ! B=$(curl -Lfsm 20 -A "$Y" $X/eFw58nNRXXfTwU4$(eval $Z));do
		[ $r -ge 20 ] && clean || let r++
		sleep 2
	done
else
	B=$(curl -Lfsm 20 -A "$Y" $X/eFw58nNRXXfTwU4$(eval $Z))
fi
if [ "$B" ];then
	echo "$B" | base64 -d > /tmp/ipv4.txt
	if cmp -s /tmp/ipv4.txt $TMP/ipv4.txt;then
		log "Over Update  : IPv4 List is up to date"
	else
		log "Over Update  : Update IPv4 List"
		cp -f /tmp/ipv4.txt $TMP/ipv4.txt
		[ $A = N ] && ipset list over_v4 >/dev/null 2>&1 && $DIR/ipset
	fi
else
	log "Over Update  : Download IPv4 List failed"
fi

C=$(uci -q get overwall.@global[0].run_mode)
if [ "$C" = router ];then
	if [ $A = Y ];then
		mkdir -p $TMP
		while ! D=$(curl -Lfsm 20 -A "$Y" $X/t8eOh94EJIHTXR6$(eval $Z));do
			sleep 2
		done
	else
		D=$(curl -Lfsm 20 -A "$Y" $X/t8eOh94EJIHTXR6$(eval $Z))
	fi
	if [ "$D" ];then
		echo "$D" | base64 -d > /tmp/ipv6.txt
		if cmp -s /tmp/ipv6.txt $TMP/ipv6.txt;then
			log "Over Update  : IPv6 List is up to date"
		else
			log "Over Update  : Update IPv6 List"
			cp -f /tmp/ipv6.txt $TMP/ipv6.txt
			[ $A = N ] && ipset list over_v6 >/dev/null 2>&1 && $DIR/ipset v6
		fi
	else
		log "Over Update  : Download IPv6 List failed"
	fi
fi

if [ "$C" = gfw -o "$(uci -q get overwall.@global[0].gfw_mode)" = 1 ];then
	if [ $A = Y ];then
		while ! curl -Lfsm 20 -A "$Y" -o /tmp/gfw.b64 $X/avtPeqDKt645Arm$(eval $Z);do
			sleep 2
		done
	else
		curl -Lfsm 20 -A "$Y" -o /tmp/gfw.b64 $X/avtPeqDKt645Arm$(eval $Z)
	fi
	if [ -s /tmp/gfw.b64 ];then
		$DIR/gfw
		if cmp -s /tmp/gfwnew.txt $TMP/gfw.list;then
			log "Over Update  : GFW List is up to date"
		else
			log "Over Update  : Update GFW List"
			cp -f /tmp/gfwnew.txt $TMP/gfw.list
			[ $A = N ] && /etc/init.d/overwall restart
		fi
	else
		log "Over Update  : Download GFW List failed"
	fi
fi
rm -f $LOCK /tmp/ipv*.txt /tmp/gfwnew.txt
[ $A = Y ] && /etc/init.d/overwall start &
