#!/bin/sh
[ "$1" = --First ] && A=Y || A=N
# 防止重複啟動
[ -f /var/lock/overwall.lock -a $A = N ] && exit 1
LOCK=/var/lock/overwall-update.lock
[ -f $LOCK ] && exit 1
touch $LOCK
DIR=/usr/share/overwall
TMP=/tmp/overwall
N=overwall
C=$(uci -q get $N.@global[0].run_mode)
D=$(uci -q get $N.@global[0].auth_3)
E=$($DIR/curl 2)
X=Overwall/rules

log(){
	[ $A = N ] && echo "$(date +'%Y-%m-%d %H:%M:%S') Over Update : $*" >> /tmp/overwall.log
}

clean(){
	local a
	[ $1 = 0 ] && a="Rules  :" || a="Update :"
	echo "$(date +'%Y-%m-%d %H:%M:%S') Over $a $2" >> /tmp/overwall.log
	rm -f $LOCK /var/lock/overwall.lock
	exit 1
}

if ! [ "$D" ];then
	uci set $N.@global[0].auth_3=$E
	uci commit
	D=$(uci -q get $N.@global[0].auth_3)
fi

if ! [ "$(uci -q get $N.@global[0].auth_1)" -a "$(uci -q get $N.@global[0].auth_2)" ];then
	clean 0 "No encrypted code or authorization code"
elif [ "$D" != "$E" ];then
	uci -q del $N.@global[0].auth_2
	uci set $N.@global[0].auth_3=$E
	uci commit
	clean 0 "Hardware code change,need new authorization code"
fi

[ $A = Y ] && mkdir -p $TMP

if [ $C = router ] || [ $C = gfw -a "$(uci -q get $N.@access_control[0].lan_gm_ips)" ] || [ $C = oversea ];then
	B=$($DIR/curl 1 $X/IPv4 "-Lfsm 20" 20 2) || clean 1 "Download IPv4 List failed!"
	echo "$B" | base64 -d > /tmp/ipv4.txt
	if cmp -s /tmp/ipv4.txt $TMP/ipv4.txt;then
		log "IPv4 List is up to date"
	else
		log "Update IPv4 List"
		cp -f /tmp/ipv4.txt $TMP/ipv4.txt
		[ $A = N ] && ipset list over_v4 >/dev/null 2>&1 && $DIR/ipset
	fi
fi

if [ $C = router ];then
	F=$($DIR/curl 1 $X/IPv6 "-Lfsm 20" 20 2) || clean 1 "Download IPv6 List failed!"
	echo "$F" | base64 -d > /tmp/ipv6.txt
	if cmp -s /tmp/ipv6.txt $TMP/ipv6.txt;then
		log "IPv6 List is up to date"
	else
		log "Update IPv6 List"
		cp -f /tmp/ipv6.txt $TMP/ipv6.txt
		[ $A = N ] && ipset list over_v6 >/dev/null 2>&1 && $DIR/ipset v6
	fi
fi

if [ $C = gfw ] || [ $C = router -a ! $(uci -q get $N.@global[0].gfw_mode) ];then
	$DIR/curl 0 $X/gfw /tmp/gfw.b64 "-Lfsm 20 -o" 20 2 || clean 1 "Download GFW List failed!"
	$DIR/gfw
	if cmp -s /tmp/gfwnew.txt $TMP/gfw.list;then
		log "GFW List is up to date"
	else
		log "Update GFW List"
		cp -f /tmp/gfwnew.txt $TMP/gfw.list
		[ $A = N ] && R=1
	fi
fi

B=$($DIR/curl 1 $X/DNS "-Lfsm 20" 20 2) || clean 1 "Download DNS List failed!"
echo "$B" | base64 -d > /tmp/dns.txt
if cmp -s /tmp/dns.txt $TMP/dns.txt;then
	log "DNS List is up to date"
else
	log "Update DNS List"
	cp -f /tmp/dns.txt $TMP/dns.txt
	[ $A = N ] && R=1
fi

[ "$R" = 1 ] && /etc/init.d/overwall restart
rm -f $LOCK /tmp/ipv*.txt /tmp/gfwnew.txt /tmp/dns.txt
[ $A = Y ] && /etc/init.d/overwall start &
