#!/bin/sh
[ "$1" = --First ] && A=Y || A=N
# 防止重複啟動
[ -f /var/lock/overwall.lock -a $A = N ] && exit 1
LOCK=/var/lock/overwall-update.lock
[ -f $LOCK ] && exit 1
touch $LOCK
DIR=/usr/share/overwall
TMP=/tmp/overwall
X=$(lua /usr/share/overwall/auth A)/2axgmlws/KkFCtZkeAP
Y=$(lua /usr/share/overwall/auth B)
Z="lua /usr/share/overwall/auth C"
N=overwall
C=$(uci -q get $N.@global[0].run_mode)
D=$(uci -q get $N.@global[0].auth_3)
E=$(lua /usr/share/overwall/auth E)

log(){
	[ $A = N ] && echo "$(date +'%Y-%m-%d %H:%M:%S') $*" >> /tmp/overwall.log
}

clean(){
	echo "$(date +'%Y-%m-%d %H:%M:%S') $*" >> /tmp/overwall.log
	rm -f $LOCK /var/lock/overwall.lock
	exit 1
}

if ! [ "$D" ];then
	uci set $N.@global[0].auth_3=$E
	uci commit
	D=$(uci -q get $N.@global[0].auth_3)
fi

if ! [ "$(uci -q get $N.@global[0].auth_1)" -a "$(uci -q get $N.@global[0].auth_2)" ];then
	clean "Over Rules     : No encrypted code or authorization code"
elif [ "$D" != "$E" ];then
	uci -q del $N.@global[0].auth_2
	uci set $N.@global[0].auth_3=$E
	uci commit
	clean "Over Rules     : Hardware code change,need new authorization code"
fi

[ $A = Y ] && mkdir -p $TMP

if [ $C = router ] || [ $C = gfw -a "$(uci -q get $N.@access_control[0].lan_gm_ips)" ] || [ $C = oversea ];then
	r=1
	while ! B=$(curl -Lfsm 20 -A "$Y" $X/eFw58nNRXXfTwU4$(eval $Z));do
		[ $r -ge 20 ] && clean "Over Rules     : Download failed" || let r++
		sleep 2
	done
	if [ "$B" ];then
		echo "$B" | base64 -d > /tmp/ipv4.txt
		if cmp -s /tmp/ipv4.txt $TMP/ipv4.txt;then
			log "Over Update  : IPv4 List is up to date"
		else
			log "Over Update  : Update IPv4 List"
			cp -f /tmp/ipv4.txt $TMP/ipv4.txt
			[ $A = N ] && ipset list over_v4 >/dev/null 2>&1 && $DIR/ipset
		fi
	else
		log "Over Update  : Download IPv4 List failed"
	fi
fi

if [ $C = router ];then
	while ! F=$(curl -Lfsm 20 -A "$Y" $X/t8eOh94EJIHTXR6$(eval $Z));do
		sleep 2
	done
	if [ "$F" ];then
		echo "$F" | base64 -d > /tmp/ipv6.txt
		if cmp -s /tmp/ipv6.txt $TMP/ipv6.txt;then
			log "Over Update  : IPv6 List is up to date"
		else
			log "Over Update  : Update IPv6 List"
			cp -f /tmp/ipv6.txt $TMP/ipv6.txt
			[ $A = N ] && ipset list over_v6 >/dev/null 2>&1 && $DIR/ipset v6
		fi
	else
		log "Over Update  : Download IPv6 List failed"
	fi
fi

if [ $C = gfw ] || [ $C = router -a ! $(uci -q get $N.@global[0].gfw_mode) ];then
	while ! curl -Lfsm 20 -A "$Y" -o /tmp/gfw.b64 $X/avtPeqDKt645Arm$(eval $Z);do
		sleep 2
	done
	if [ -s /tmp/gfw.b64 ];then
		$DIR/gfw
		if cmp -s /tmp/gfwnew.txt $TMP/gfw.list;then
			log "Over Update  : GFW List is up to date"
		else
			log "Over Update  : Update GFW List"
			cp -f /tmp/gfwnew.txt $TMP/gfw.list
			[ $A = N ] && /etc/init.d/overwall restart
		fi
	else
		log "Over Update  : Download GFW List failed"
	fi
fi
rm -f $LOCK /tmp/ipv*.txt /tmp/gfwnew.txt
[ $A = Y ] && /etc/init.d/overwall start &
