#!/bin/sh
GET(){
	echo $3 $(curl -LfsH "Authorization: Bearer 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" https://api.github.com/repos/$1/git/refs/heads/$2 | grep '"sha"' | awk '{print $2}' | sed -e 's/"//g' -e 's/,//g') >> SHA
}

A="zfl9/chinadns-ng|master|chinadns-ng
llccd/netfilter-full-cone-nat|dev|fullconenat
aarond10/https_dns_proxy|master|https_dns_proxy
zfl9/ipt2socks|master|ipt2socks
rofl0r/microsocks|master|microsocks
n42n/n3n|main|n3n
OpenVPN/easy-rsa|master|openvpn-easy-rsa
code4craft/pdnsd|master|pdnsd
semigodking/redsocks|master|redsocks2
aircrack-ng/rtl8812au|v5.6.4.2|rtl8812au-ac
shadowsocksrr/shadowsocksr-libev|Akkariiin/master|shadowsocksr-libev
shadowsocks/simple-obfs|master|simple-obfs
peter-tank/trojan-plus|master|trojan-plus
Wind4/vlmcsd|master|vlmcsd
teddysun/xray-plugin|main|xray-plugin
openwrt/rtl8125|master|rtl8125
openwrt/rtl8126|master|rtl8126
openwrt/rtl8168|master|rtl8168
fatedier/frp|dev|frp
xtaci/kcptun|master|kcptun
shadowsocks/shadowsocks-libev|master|shadowsocks-libev
tohojo/sqm-scripts|main|sqm-scripts
XTLS/Xray-core|main|xray
zerotier/ZeroTierOne|dev|zerotier
pymumu/smartdns|master|smartdns
miniupnp/miniupnp|master|miniupnp
liudf0716/xfrpc|master|xfrpc"
rm -f SHA
for i in $A;do
	i=$(echo $i | sed 's/|/ /g')
	GET $i
done
