#!/bin/sh
GET(){
	echo $3 $(curl -LfsH "Authorization: Bearer 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" https://api.github.com/repos/$1/git/refs/heads/$2 | grep '"sha"' | awk '{print $2}' | sed -e 's/"//g' -e 's/,//g') >> SHA
}

A="zfl9/chinadns-ng|master|chinadns-ng
llccd/netfilter-full-cone-nat|dev|fullconenat
aarond10/https_dns_proxy|master|https_dns_proxy
zfl9/ipt2socks|master|ipt2socks
rofl0r/microsocks|master|microsocks
ntop/n2n|dev|n2n
OpenVPN/easy-rsa|master|openvpn-easy-rsa
code4craft/pdnsd|master|pdnsd
semigodking/redsocks|master|redsocks2
aircrack-ng/rtl8812au|v5.6.4.2|rtl8812au-ac
shadowsocksrr/shadowsocksr-libev|Akkariiin/master|shadowsocksr-libev
shadowsocks/simple-obfs|master|simple-obfs
peter-tank/trojan-plus|master|trojan-plus
Wind4/vlmcsd|master|vlmcsd
teddysun/xray-plugin|main|xray-plugin
fatedier/frp|dev|frp
xtaci/kcptun|master|kcptun
shadowsocks/shadowsocks-libev|master|shadowsocks-libev
tohojo/sqm-scripts|master|sqm-scripts
XTLS/Xray-core|main|xray
zerotier/ZeroTierOne|dev|zerotier
pymumu/smartdns|master|smartdns"
rm -f SHA
for i in $A;do
	i=$(echo $i | sed 's/|/ /g')
	GET $i
done
sed -i 's/655c53d27df0bd69e0ecfa8309ce2940797f3362/8f6cb0911b9b4bcb00dfe1cd368c1cec1137e9e5/' SHA #microsocks
