#!/bin/sh
if [ "$ACTION" = ifup -a "$INTERFACE" != wan_6 ];then
	if uci -q get overwall.@global[0].global_server >/dev/null;then
		if pidof smartdns >/dev/null;then
			killall -q -9 smartdns
			$(which smartdns) -f -c /var/etc/smartdns/smartdns.conf >/dev/null 2>&1 &
		fi
	fi
fi
