#!/bin/sh
# 防止重複啟動
LOCK=/var/lock/adblock.lock
if [ -f $LOCK ];then
	case $1 in
		gen|addown)X=1;;
		*)exit 1;;
	esac
fi
touch $LOCK

A="Download Adblock Plus Rules"
B="Download Subscribe Rules"
C=0
D=0
E="date +'%Y-%m-%d %H:%M:%S'"
U=`uci -q get adblock.@adblock[0].url`
O=/tmp/ad.conf
P=/tmp/adblock
W=`cat /etc/adblock/white.list`
H=ad-rules
I="-Lfsm 20 -o"

gen(){
	for i in $W;do sed -i -e "/\/$i\//d" -e "/\.$i\//d" $O;done
}

down(){
	G=/tmp/ad_tmp/3rd
	F=$G/ad_new.conf
	rm -rf ${G%/*}
	mkdir -p $G
	for i in $U;do
		case $i in
			adguard|anti-ad|ad-wars)K="/usr/share/overwall/curl 0 $H/$i $F '$I' 20 2";;
			*)K="curl $I $F $i";;
		esac
		if ! eval $K;then
			echo "`eval $E` [Download $i failed]";continue
		fi
		X=`md5sum $G/3rd.conf 2>/dev/null | awk '{print$1}'`
		Y=`md5sum $G/host 2>/dev/null | awk '{print$1}'`
		case $i in
			adguard|anti-ad|ad-wars);;
			*)sed -i 's/\r/\n/g' $F;sed -i -e '/127.0.0.1 #/d' -e '/127.0.0.1 !/d' -e 's:#.*::' -e 's:!.*::' -e 's/\$.*//g' -e 's/[ \t]*$//g' -e 's/^[ \t]*//g' -e '/\*/d' -e '/^$/d' $F;;
		esac
		if grep -q "^address=" $F;then
			cat $F >> $G/3rd.conf
		elif grep -q -e "^0.0.0.0 " -e "^127.0.0.1 " $F;then
			cat $F >> $G/host
		elif ! grep -q -e "|" -e "@" $F;then
			cat $F | sed -e 's:^:address=/:' -e 's:$:/:' >> $G/3rd.conf
		else
			cat $F | grep ^\|\|[^\*]*\^$ | grep -Ev "^\|\|[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}*" | sed -e 's:||:address=/:' -e 's:\^:/:' >> $G/3rd.conf
		fi
		[ "$X" = "`md5sum $G/3rd.conf 2>/dev/null | awk '{print$1}'`" -a "$Y" = "`md5sum $G/host 2>/dev/null | awk '{print$1}'`" ] && echo "`eval $E` [Conversion $i failed]"
		echo $i >> $G/url
	done
	[ -s $G/host ] && sed -e '/:/d' -e '/ 0.0.0.0/d' -e '/255.255.255.255/d' -e '/ local/d' -e 's:127.0.0.1 :address=/:' -e 's:0.0.0.0 :address=/:' -e 's:$:/:' $G/host >> $G/3rd.conf
	[ -s $G/3rd.conf ] && sed -i -e 's:/127.0.0.1$:/:' -e 's:/0.0.0.0$:/:' $G/3rd.conf && echo "`sort -u $G/3rd.conf`" > $G/3rd.conf
	[ -s $G/url ] && echo "`sort -u $G/url`" > $G/url
	if [ -s $G/3rd.conf -a -s $P/adblock.conf ];then
		echo "`sort -u $G/3rd.conf $P/adblock.conf`" > $G/3rd.conf
		echo "`sort $G/3rd.conf $P/adblock.conf | uniq -u`" > $G/3rd.conf
	fi
	if [ -s $G/3rd.conf ];then
		echo "`eval $E` [$B successful]"
		rm -f $F $G/host $P/failed
		for i in $W;do sed -i -e "/\/$i\//d" -e "/\.$i\//d" $G/3rd.conf;done
		[ "$1" = 2 ] && rm -f $LOCK && exit
		X=`uci -q get adblock.@adblock[0].flash`
		Y=`md5sum $G/* | awk '{print$1}'`
		[ $X = 0 ] && Z=`md5sum $P/3rd/* 2>/dev/null | awk '{print$1}'` || Z=`md5sum /etc/adblock/3rd/* 2>/dev/null | awk '{print$1}'`
		if [ "$Y" != "$Z" ];then
			[ "$1" = 1 ] || echo "`eval $E` [Subscribe Rules need update]"
			if [ "$X" = 0 ];then
				rm -f $P/3rd/*
				cp -a $G $P
			else
				rm -f /etc/adblock/3rd/*
				cp -a $G /etc/adblock
			fi
			D=1
		else
			echo "`eval $E` [Subscribe Rules no change]"
		fi
	else
		echo "`eval $E` [$B failed]"
		echo failed > $P/failed
		[ "$1" = 2 ] && rm -f $LOCK && exit
	fi
	rm -rf ${G%/*}
}

case $1 in
	addown)down 1;exit;;
	down)down 2;;
	gen)gen;[ "$X" = 1 ] || rm -f $LOCK;exit;;
esac

if [ `uci -q get adblock.@adblock[0].enable` = 1 ];then
	echo "`eval $E` [$A]"
	if /usr/share/overwall/curl 0 $H/dnsmasq.adblock $O "$I" 20 2;then
		echo "`eval $E` [$A successful]"
		gen
		if cmp -s $O $P/adblock.conf;then
			echo "`eval $E` [Adblock Plus Rules no change]"
		else
			echo "`eval $E` [Adblock Plus Rules need update]"
			mv -f $O $P/adblock.conf
			C=1
		fi
	else
		echo "`eval $E` [$A failed]"
	fi
	rm -f $O
	[ "$U" ] && echo "`eval $E` [$B]" && down
	echo `eval $E` > $P/adblock.updated
fi

if [ $C = 1 -o $D = 1 ];then
	echo "`eval $E` [Reload Adblock Plus Rules]"
	/etc/init.d/adblock restart
fi

rm -f $LOCK
