#!/bin/sh
[ "$1" = --down ] || exit 1
# 防止重複啟動
LOCK=/var/lock/adblock.lock
[ -f $LOCK ] && exit 1
touch $LOCK

A=/tmp/adblock
B=/tmp/adupdate.log
C="date +'%Y-%m-%d %H:%M:%S'"
D="Download Adblock Plus Rules"
H=$(lua /usr/share/adblock/auth A)/ad-rules
I=$(lua /usr/share/adblock/auth B)
J="lua /usr/share/adblock/auth C"

clean(){
	echo "`eval $C` [$D failed]" >> $B
	rm -f $LOCK
	exit 1
}

if [ "$2" = 1 ];then
	mkdir -p $A
	echo "`eval $C` [Check network status]" > $B
	while ! curl -so /dev/null -m 3 www.baidu.com;do
		cat $B | grep -q Wait || echo "`eval $C` [Wait for network to connect]" >> $B
		sleep 2
	done
	echo "`eval $C` [Check network status successful]" >> $B
	echo "`eval $C` [$D]" >> $B
	X=1
	while ! curl --connect-timeout 5 -m 20 -A "$I" -Lfso $A/adblock.conf $H/dnsmasq.adblock$(eval $J);do
		[ $X -ge 20 ] && clean || let X++
		sleep 2
	done
	echo "`eval $C` [$D successful]" >> $B
	for i in $(cat /etc/adblock/white.list);do sed -i -e "/\/$i\//d" -e "/\.$i\//d" $A/adblock.conf;done
fi

if [ "$3" = 1 ];then
	echo "`eval $C` [Download Subscribe Rules]" >> $B
	/usr/share/adblock/adblock addown >> $B
fi

echo "`eval $C` [Start Adblock Plus+]" >> $B;echo "`eval $C`" > $A/adblock.updated
rm -f $LOCK
/etc/init.d/adblock start &
