#!/bin/sh /etc/rc.common
START=60
STOP=10
A="sysctl -w net.ipv4.tcp_congestion_control"

bbr(){
	if [ "$(uci -q get flowoffload.@flowoffload[0].bbr)" = 1 ];then
		$A=bbr
	else
		$A=cubic
	fi
}

start(){
	bbr
}

stop(){
	bbr
}
