#!/bin/sh /etc/rc.common
START=99

start()
{
	a=$(cat /proc/cpuinfo | grep name | cut -f2 -d: | uniq)
	b=$(echo -n ' : ')
	c=$(cat /proc/cpuinfo | grep 'core id' | sort -u | wc -l)
	d=$(echo -n ' Core ')
	e=$(cat /proc/cpuinfo | grep 'processor' | wc -l)
	f=$(echo -n ' Thread ')
	g=${a}${b}${c}${d}${e}${f}
	mkdir -p /tmp/sysinfo
	echo $g > /tmp/sysinfo/model

	for i in $(ip address | awk -F ': ' '/eth[0-9]+/ {print $2}' | grep -Ev "@|\." | xargs);do
		ethtool -K $i rx-checksum on 2>/dev/null
		ethtool -K $i tx-checksum-ip-generic on 2>/dev/null || {
			ethtool -K $i tx-checksum-ipv4 on 2>/dev/null
			ethtool -K $i tx-checksum-ipv6 on 2>/dev/null
		}
		ethtool -K $i tx-scatter-gather on 2>/dev/null
		ethtool -K $i gso on 2>/dev/null
		ethtool -K $i tso on 2>/dev/null
		ethtool -K $i ufo on 2>/dev/null
	done
	true
}
